services:
  maply-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VERSION=20-alpine
    image: maply-backend:latest
    environment:
      - NODE_ENV=production
      - PORT=8080
    ports:
      - "8081:8080" # expose container 8080 as host 8081
    healthcheck:
      test: [ "CMD", "node", "-e", "require('http').get('http://localhost:8080/health', r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    restart: unless-stopped
